#ifndef ASSETS_H
#define ASSETS_H

#include "core/image.h"

#define ASSETS_IMAGE_PATH "Graphics"

#define ASSET_EXTERNAL_FILE_LIST "***EXTERNAL_FILES***"

#define PATH_ROTATE_OFFSET 56

typedef enum {
	ASSET_HIGHWAY_BASE_START,
	ASSET_HIGHWAY_BARRIER_START,
	ASSET_AQUEDUCT_WITH_WATER,
	ASSET_AQUEDUCT_WITHOUT_WATER,
	ASSET_GOLD_SHIELD,
	ASSET_HAGIA_SOPHIA_FIX,
	ASSET_FIRST_ORNAMENT,
	ASSET_CENTER_CAMERA_ON_BUILDING,
	ASSET_OX,
	ASSET_UI_RISKS,
	ASSET_UI_SELECTION_CHECKMARK,
	ASSET_UI_SELECTION_CROSS,
	ASSET_UI_VERTICAL_EMPIRE_PANEL,
	ASSET_UI_GEAR_ICON,
	ASSET_UI_COPY_ICON,
	ASSET_UI_PASTE_ICON,
	ASSET_UI_ASCEPIUS,
	ASSET_UI_EMP_ICON_1,
	ASSET_UI_EMP_ICON_2,
	ASSET_UI_EMP_ICON_3,
	ASSET_UI_EMP_ICON_4,
	ASSET_UI_EMP_ICON_5,
	ASSET_UI_EMP_ICON_6,
	ASSET_UI_EMP_ICON_7,
	ASSET_UI_EMP_ICON_8,
	ASSET_UI_EMP_ICON_9,
	ASSET_UI_EMP_ICON_10,
	ASSET_UI_EMP_ICON_11,
	ASSET_UI_EMP_ICON_12,
	ASSET_UI_EMP_ICON_13,
	ASSET_UI_EMP_ICON_OLD_WATCHTOWER,
	ASSET_UI_FOUNTAIN_RANGE,
	ASSET_UI_RESERVOIR_RANGE,
	ASSET_UI_GRID,
	ASSET_UI_CENTERED_BOAT,
	ASSET_UI_CENTERED_CART,
	ASSET_UI_CART_AND_BOAT,
	ASSET_UI_ARROW_UP,
	ASSET_UI_ARROW_DOWN,
	ASSET_UI_EMP_PANEL_HOR,
	ASSET_UI_EMP_PANEL_VER,
	ASSET_UI_EMP_PANEL_XBAR_DRAG,
	ASSET_UI_BTN_MENU_LEFT_PANEL,
	ASSET_UI_BTN_MENU_MIDDLE_PANEL,
	ASSET_UI_BTN_MENU_RIGHT_PANEL,
	ASSET_UI_BTN_MENU_LEFT_PANEL_MIRROR_V,
	ASSET_UI_BTN_MENU_MIDDLE_PANEL_MIRROR_V,
	ASSET_UI_BTN_MENU_RIGHT_PANEL_MIRROR_V,
	ASSET_UI_BTN_MENU_FRAME_01,
	ASSET_UI_BTN_MENU_FRAME_02,
	ASSET_UI_BTN_MENU_FRAME_03,
	ASSET_UI_BTN_MENU_FRAME_04,
	ASSET_UI_BTN_MENU_FRAME_06,
	ASSET_UI_BTN_MENU_FRAME_07,
	ASSET_UI_BTN_MENU_FRAME_08,
	ASSET_UI_BTN_MENU_FRAME_09,
	ASSET_UI_SORTING_ICON,
	ASSET_UI_FILTER_ICON,
	ASSET_UI_SORTING_ICON_HOVER,
	ASSET_UI_FILTER_ICON_HOVER,
	ASSET_UI_ARROW_MASKED_UP,
	ASSET_UI_ARROW_MASKED_DOWN,
	ASSET_UI_TRADE_LEDGER,
	ASSET_UI_TRADE_LEDGER_HOVER,
	ASSET_UI_TRADE_LEDGER_BUTTON_IDLE,
	ASSET_UI_TRADE_LEDGER_BUTTON_HOVER,
	ASSET_UI_DIAGONAL_LINES_L,
	ASSET_UI_DIAGONAL_LINES_R,
	ASSET_UI_FONT_BROWN_UP_ARROW,
	ASSET_UI_FONT_BROWN_DOWN_ARROW,
	ASSET_UI_TRADE_LEDGER_EXPORT,
	ASSET_UI_TRADE_LEDGER_IMPORT,
	ASSET_UI_RESOURCE_PICKER,
	ASSET_UI_SCROLLBAR_UP,
	ASSET_UI_SCROLLBAR_DOWN,
	ASSET_UI_SCROLLBAR_MIDDLE,
	ASSET_UI_SCROLLBAR_LINES_ALPHA,
	ASSET_UI_SCROLLBAR_MIDDLE_01_END_TOP,
	ASSET_UI_SCROLLBAR_MIDDLE_01_END_BOTTOM,
	ASSET_UI_SCROLLBAR_MIDDLE_01_TRIMMED,
	ASSET_UI_SCROLLBAR_MIDDLE_01_TRIMMED_MIRROR,
	ASSET_UI_SCROLLBAR_MIDDLE_02_END_TOP,
	ASSET_UI_SCROLLBAR_MIDDLE_02_END_BOTTOM,
	ASSET_UI_SCROLLBAR_MIDDLE_02_TRIMMED,
	ASSET_UI_SCROLLBAR_MIDDLE_02_TRIMMED_MIRROR,
	ASSET_UI_SCROLLBAR_MIDDLE_03_END_TOP,
	ASSET_UI_SCROLLBAR_MIDDLE_03_END_BOTTOM,
	ASSET_UI_SCROLLBAR_MIDDLE_03_TRIMMED,
	ASSET_UI_SCROLLBAR_MIDDLE_03_TRIMMED_MIRROR,
	ASSET_UI_SCROLLBAR_MIDDLE_04_END_TOP,
	ASSET_UI_SCROLLBAR_MIDDLE_04_END_BOTTOM,
	ASSET_UI_SCROLLBAR_MIDDLE_04_TRIMMED,
	ASSET_UI_SCROLLBAR_MIDDLE_04_TRIMMED_MIRROR,
	ASSET_UI_SCROLLBAR_MIDDLE_01B_END_LEFT,
	ASSET_UI_SCROLLBAR_MIDDLE_01B_END_RIGHT,
	ASSET_UI_SCROLLBAR_MIDDLE_01B_TRIMMED,
	ASSET_UI_SCROLLBAR_MIDDLE_01B_TRIMMED_MIRROR,
	ASSET_UI_SCROLLBAR_MIDDLE_02B_END_LEFT,
	ASSET_UI_SCROLLBAR_MIDDLE_02B_END_RIGHT,
	ASSET_UI_SCROLLBAR_MIDDLE_02B_TRIMMED,
	ASSET_UI_SCROLLBAR_MIDDLE_02B_TRIMMED_MIRROR,
	ASSET_UI_SCROLLBAR_MIDDLE_03B_END_LEFT,
	ASSET_UI_SCROLLBAR_MIDDLE_03B_END_RIGHT,
	ASSET_UI_SCROLLBAR_MIDDLE_03B_TRIMMED,
	ASSET_UI_SCROLLBAR_MIDDLE_03B_TRIMMED_MIRROR,
	ASSET_UI_SCROLLBAR_MIDDLE_04B_END_LEFT,
	ASSET_UI_SCROLLBAR_MIDDLE_04B_END_RIGHT,
	ASSET_UI_SCROLLBAR_MIDDLE_04B_TRIMMED,
	ASSET_UI_SCROLLBAR_MIDDLE_04B_TRIMMED_MIRROR,
	ASSET_UI_SCROLL_BG_01,
	ASSET_UI_SCROLL_BG_02,
	ASSET_UI_SCROLL_BG_03,
	ASSET_AESTHETIC_BUILDING_WILLOW_TREE,
	ASSET_MAX_KEY
} asset_id;

typedef enum {
	ASSET_FONT_NONE, // 14000 - equal to IMAGE_FONT_CUSTOM_OFFSET
	ASSET_FONT_SQ_BRACKET_LEFT,
	ASSET_FONT_SQ_BRACKET_RIGHT,
	ASSET_FONT_CRLY_BRACKET_LEFT,
	ASSET_FONT_CRLY_BRACKET_RIGHT,
	ASSET_FONT_ABSTRACT_CARET_SYMBOL,
	ASSET_FONT_MAX_KEY
} asset_font_id;

void assets_init(int force_reload, color_t **main_images, int *main_image_widths);

int assets_load_single_group(const char *file_name, color_t **main_images, int *main_image_widths);

int assets_get_group_id(const char *assetlist_name);

int assets_get_image_id(const char *assetlist_name, const char *image_name);

int assets_get_external_image(const char *path, int force_reload);

int assets_lookup_image_id(asset_id id);

const image *assets_get_image(int image_id);

const image *assets_get_font_image(int letter_id);

void assets_load_unpacked_asset(int image_id);

#endif // ASSETS_H
